#!/bin/bash
# paullm-ssh host setup script
# Configures a Mac as an SSH development host for AI coding tools.
#
# Supported tools: Claude, OpenCode, Codex, and any SSH-based agent.
#
# Usage:
#   ./scripts/setup-ssh-host.sh           # Interactive setup
#   ./scripts/setup-ssh-host.sh --auto  # Non-interactive with defaults

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

AUTO_MODE="${AUTO_MODE:-0}"
DRY_RUN="${DRY_RUN:-0}"
CREATE_AI_USER="${CREATE_AI_USER:-0}"
AI_USERNAME="${AI_USERNAME:-developer}"
SSH_PORT="${SSH_PORT:-22}"
KEY_TYPE="${KEY_TYPE:-ed25519}"
AI_USER_ADMIN="${AI_USER_ADMIN:-0}"

# ── helpers ─────────────────────────────────────────────────────────
log_info()  { echo -e "${BLUE}[INFO]${NC}  $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}   $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()  { echo -e "\n${CYAN}▸ $1${NC}"; }

check_macos() {
    if [[ "$(uname -s)" != "Darwin" ]]; then
        log_error "This script is designed for macOS only."
        exit 1
    fi
}

backup_file() {
    local file="$1"
    if [[ -f "$file" && ! -f "${file}.backup" ]]; then
        if [[ "$DRY_RUN" -eq 0 ]]; then
            cp "$file" "${file}.backup"
            log_info "Backed up $file to ${file}.backup"
        fi
    fi
}

run_or_dry() {
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log_info "[DRY-RUN] Would run: $*"
    else
        "$@"
    fi
}

# ── interactive prompts ─────────────────────────────────────────────
prompt_yesno() {
    local prompt="$1"
    local default="${2:-y}"
    if [[ "$AUTO_MODE" -eq 1 ]]; then
        echo "$default"
        return 0
    fi
    local answer
    read -r -p "$prompt [Y/n]: " answer
    answer="${answer:-$default}"
    [[ "$answer" =~ ^[Yy]$ ]]
}

# ── main setup steps ────────────────────────────────────────────────

step_enable_remote_login() {
    log_step "Enabling Remote Login (SSH)"

    local is_enabled
    is_enabled=$(sudo systemsetup -getremotelogin 2>/dev/null | grep -i "On" || true)

    if [[ -n "$is_enabled" ]]; then
        log_ok "Remote Login is already enabled"
        return 0
    fi

    log_info "Remote Login is currently off. Enabling..."
    if [[ "$DRY_RUN" -eq 1 ]]; then
        log_info "[DRY-RUN] Would run: sudo systemsetup -setremotelogin on"
    else
        sudo systemsetup -setremotelogin on
        log_ok "Remote Login enabled"
    fi
}

step_check_sshd() {
    log_step "Checking SSH daemon"

    if sudo launchctl print system/com.openssh.sshd &>/dev/null; then
        log_ok "sshd service is loaded"
    else
        log_warn "sshd service not found in launchctl. It may be managed differently on this macOS version."
    fi

    if nc -z localhost "$SSH_PORT" 2>/dev/null || true; then
        log_ok "SSH is listening on port $SSH_PORT"
    else
        log_warn "Cannot verify SSH port $SSH_PORT is listening (may need a moment to start)"
    fi
}

step_configure_sshd() {
    log_step "Configuring SSH daemon"

    local sshd_config="/etc/ssh/sshd_config"
    local sshd_config_d="/etc/ssh/sshd_config.d"
    local paullm_config="/etc/ssh/sshd_config.d/99-paullm-ssh.conf"

    # Prefer sshd_config.d if it exists (macOS 13+)
    if [[ -d "$sshd_config_d" ]]; then
        backup_file "$sshd_config"
        if [[ ! -f "$paullm_config" ]]; then
            log_info "Creating $paullm_config"
            if [[ "$DRY_RUN" -eq 0 ]]; then
                sudo tee "$paullm_config" > /dev/null <<'EOF'
# paullm-ssh host configuration for AI coding tools
# Generated by scripts/setup-ssh-host.sh

# Only allow key-based authentication for AI tool access
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Disable root login
PermitRootLogin no

# Use secure defaults
Protocol 2
X11Forwarding no
PrintMotd no
AcceptEnv LANG LC_*

# Allow reasonable number of connections for multi-tab tools
MaxSessions 50
MaxStartups 30:30:100

# Keep connections alive for long-running AI sessions
ClientAliveInterval 60
ClientAliveCountMax 10

# Allow TCP forwarding for port-forwarding workflows
AllowTcpForwarding yes
EOF
            fi
            log_ok "Created paullm-ssh sshd config"
        else
            log_ok "paullm-ssh sshd config already exists"
        fi
    else
        # Fallback: edit main sshd_config
        backup_file "$sshd_config"
        log_warn "Using legacy sshd_config editing (no sshd_config.d support)"
        # We won't auto-edit the main file to avoid breaking things
        log_warn "Please manually add these lines to $sshd_config:"
        echo "  PasswordAuthentication no"
        echo "  PermitRootLogin no"
        echo "  ClientAliveInterval 60"
    fi

    # Validate config
    if [[ "$DRY_RUN" -eq 0 ]]; then
        if sudo sshd -t 2>/dev/null; then
            log_ok "SSH configuration is valid"
        else
            log_warn "SSH configuration test produced warnings (may be normal)"
        fi
    fi
}

step_setup_firewall() {
    log_step "Configuring firewall"

    local fw_state
    fw_state=$(sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate 2>/dev/null | grep -i "enabled" || true)

    if [[ -n "$fw_state" ]]; then
        log_ok "Application firewall is enabled"
    else
        log_info "Application firewall is off. Enabling..."
        run_or_dry sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
        log_ok "Firewall enabled"
    fi

    # Allow sshd through firewall
    if [[ -f "/usr/libexec/ssh-keysign-wrapper" ]]; then
        run_or_dry sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "/usr/libexec/ssh-keysign-wrapper"
    fi

    log_ok "Firewall configured for SSH"
}

step_generate_host_keys() {
    log_step "Checking host SSH keys"

    local host_key_dir="/etc/ssh"
    local key_types=("ssh_host_ed25519_key" "ssh_host_rsa_key")
    local generated=0

    for key in "${key_types[@]}"; do
        if [[ ! -f "$host_key_dir/$key" ]]; then
            log_info "Generating host key: $key"
            if [[ "$DRY_RUN" -eq 0 ]]; then
                local key_type
                key_type="$(echo "$key" | sed 's/^ssh_host_//' | sed 's/_key$//')"
                sudo ssh-keygen -t "$key_type" -f "$host_key_dir/$key" -N "" -C "paullm-ssh-host@$(hostname)"
            fi
            generated=1
        fi
    done

    if [[ "$generated" -eq 0 ]]; then
        log_ok "Host SSH keys already present"
    fi
}

step_create_ai_user() {
    if [[ "$CREATE_AI_USER" -eq 0 ]]; then
        return 0
    fi

    log_step "Setting up AI developer user: $AI_USERNAME"

    if id "$AI_USERNAME" &>/dev/null; then
        log_ok "User '$AI_USERNAME' already exists"
    else
        log_info "Creating user '$AI_USERNAME'..."
        if [[ "$DRY_RUN" -eq 0 ]]; then
            # Create a standard user, hidden from login window.
            # Pass -admin only when explicitly opted in via --ai-user-admin.
            local sysadmin_args=(
                -addUser "$AI_USERNAME"
                -fullName "AI Developer"
                -password "-"
            )
            if [[ "$AI_USER_ADMIN" -eq 1 ]]; then
                sysadmin_args+=( -admin )
            fi
            sudo sysadminctl "${sysadmin_args[@]}" || true
            sudo dscl . create /Users/"$AI_USERNAME" UserShell /bin/zsh
            sudo dscl . create /Users/"$AI_USERNAME" NFSHomeDirectory /Users/"$AI_USERNAME"
            sudo mkdir -p /Users/"$AI_USERNAME"
            sudo chown "$AI_USERNAME:staff" /Users/"$AI_USERNAME"
        fi
        log_ok "Created user '$AI_USERNAME'"
    fi

    # Set up SSH directory
    local ai_ssh_dir="/Users/$AI_USERNAME/.ssh"
    if [[ "$DRY_RUN" -eq 0 ]]; then
        sudo mkdir -p "$ai_ssh_dir"
        sudo chmod 700 "$ai_ssh_dir"
    fi
}

step_generate_client_key() {
    log_step "Generating client SSH key for AI tools"

    local target_user="$AI_USERNAME"
    if [[ "$CREATE_AI_USER" -eq 0 ]]; then
        target_user="$(whoami)"
    fi

    local ssh_dir
    if [[ "$target_user" == "$(whoami)" ]]; then
        ssh_dir="$HOME/.ssh"
    else
        ssh_dir="/Users/$target_user/.ssh"
    fi

    run_or_dry mkdir -p "$ssh_dir"
    run_or_dry chmod 700 "$ssh_dir"

    local key_file="$ssh_dir/paullm_${target_user}_ed25519"

    if [[ -f "$key_file" ]]; then
        log_ok "AI tool key already exists: $key_file"
    else
        log_info "Generating Ed25519 key pair..."
        if [[ "$DRY_RUN" -eq 0 ]]; then
            ssh-keygen -t ed25519 -f "$key_file" -N "" -C "paullm-ssh-$(hostname)-$target_user"
        fi
        log_ok "Generated key: $key_file"
    fi

    # Show public key
    if [[ -f "${key_file}.pub" ]]; then
        echo ""
        echo "  Public key to add to remote servers:"
        echo "  $(cat "${key_file}.pub")"
        echo ""
    fi
}

step_install_authorized_key() {
    log_step "Installing authorized key"

    local target_user="$AI_USERNAME"
    if [[ "$CREATE_AI_USER" -eq 0 ]]; then
        target_user="$(whoami)"
    fi

    local ssh_dir auth_keys
    if [[ "$target_user" == "$(whoami)" ]]; then
        ssh_dir="$HOME/.ssh"
        auth_keys="$ssh_dir/authorized_keys"
    else
        ssh_dir="/Users/$target_user/.ssh"
        auth_keys="$ssh_dir/authorized_keys"
    fi

    local key_file="$ssh_dir/paullm_${target_user}_ed25519"

    if [[ ! -f "${key_file}.pub" ]]; then
        log_warn "Public key not found, skipping authorized_keys setup"
        return 0
    fi

    local pub_key
    pub_key="$(cat "${key_file}.pub")"

    if [[ -f "$auth_keys" ]] && grep -q "$pub_key" "$auth_keys" 2>/dev/null; then
        log_ok "Key already in authorized_keys"
    else
        log_info "Adding public key to $auth_keys"
        if [[ "$DRY_RUN" -eq 0 ]]; then
            if [[ "$target_user" == "$(whoami)" ]]; then
                echo "$pub_key" >> "$auth_keys"
                chmod 600 "$auth_keys"
            else
                sudo tee -a "$auth_keys" > /dev/null <<< "$pub_key"
                sudo chmod 600 "$auth_keys"
                sudo chown "$target_user:staff" "$auth_keys"
            fi
        fi
        log_ok "Installed authorized key"
    fi
}

step_setup_ssh_config() {
    log_step "Setting up local SSH config snippets"

    local user_ssh_dir="$HOME/.ssh"
    local config_file="$user_ssh_dir/config"

    run_or_dry mkdir -p "$user_ssh_dir"

    local host_ip
    host_ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "YOUR_MAC_IP")"

    local snippet="$user_ssh_dir/config.d/paullm-host"
    run_or_dry mkdir -p "$user_ssh_dir/config.d"

    if [[ -f "$snippet" ]]; then
        log_ok "SSH config snippet already exists: $snippet"
    else
        log_info "Creating SSH config snippet for AI tools..."
        if [[ "$DRY_RUN" -eq 0 ]]; then
            cat > "$snippet" <<EOF
# paullm-ssh host configuration
# This machine ($(hostname)) configured for AI coding tools
#
# Add this to your ~/.ssh/config on the machine running the AI tool:
#
# Host $(hostname)-dev
#     HostName $host_ip
#     User $(whoami)
#     Port $SSH_PORT
#     IdentityFile ~/.ssh/paullm_$(whoami)_ed25519
#     AddKeysToAgent yes
#     UseKeychain yes
#     ServerAliveInterval 60
#     ServerAliveCountMax 10
#
# Tool-specific notes:
#   Claude Code: Run 'claude' in the project directory after SSHing
#   OpenCode:   Use the terminal view in the app (uses this host)
#   Codex:      Set SSH_HOST=$(hostname)-dev in your environment
EOF
        fi
        log_ok "Created config snippet: $snippet"
    fi

    # Ensure Include is in main config
    if [[ -f "$config_file" ]]; then
        if ! grep -q "Include config.d/paullm-host" "$config_file" 2>/dev/null; then
            log_info "Adding Include directive to $config_file"
            if [[ "$DRY_RUN" -eq 0 ]]; then
                # Prepend include
                local temp_config
                temp_config="$(mktemp)"
                echo "Include config.d/paullm-host" > "$temp_config"
                echo "" >> "$temp_config"
                cat "$config_file" >> "$temp_config"
                mv "$temp_config" "$config_file"
                chmod 600 "$config_file"
            fi
        fi
    else
        log_info "Creating $config_file"
        if [[ "$DRY_RUN" -eq 0 ]]; then
            echo "Include config.d/paullm-host" > "$config_file"
            chmod 600 "$config_file"
        fi
    fi
}

step_print_summary() {
    log_step "Setup Summary"

    local host_ip
    host_ip="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "YOUR_MAC_IP")"
    local target_user="$AI_USERNAME"
    if [[ "$CREATE_AI_USER" -eq 0 ]]; then
        target_user="$(whoami)"
    fi

    echo ""
    echo -e "${GREEN}Your Mac is configured as an SSH development host!${NC}"
    echo ""
    echo "  Hostname:     $(hostname)"
    echo "  IP Address:   $host_ip"
    echo "  SSH Port:     $SSH_PORT"
    echo "  User:         $target_user"
    echo "  Key File:     ~/.ssh/paullm_${target_user}_ed25519"
    echo ""
    echo -e "${CYAN}Connection string for AI tools:${NC}"
    echo "  ssh -p $SSH_PORT -i ~/.ssh/paullm_${target_user}_ed25519 ${target_user}@${host_ip}"
    echo ""
    echo -e "${CYAN}Add to ~/.ssh/config on your AI tool machine:${NC}"
    echo ""
    echo "  Host $(hostname)-dev"
    echo "      HostName $host_ip"
    echo "      User $target_user"
    echo "      Port $SSH_PORT"
    echo "      IdentityFile ~/.ssh/paullm_${target_user}_ed25519"
    echo "      ServerAliveInterval 60"
    echo "      ServerAliveCountMax 10"
    echo ""
    echo -e "${CYAN}Tool-specific quick starts:${NC}"
    echo ""
    echo "  Claude Code:"
    echo "      ssh $(hostname)-dev"
    echo "      cd ~/your-project && claude"
    echo ""
    echo "  OpenCode:"
    echo "      Use '$(hostname)-dev' as the host in connection settings"
    echo ""
    echo "  Codex (OpenAI):"
    echo "      export SSH_HOST=$(hostname)-dev"
    echo ""
    echo -e "${YELLOW}Important:${NC}"
    echo "  - The private key is at: ~/.ssh/paullm_${target_user}_ed25519"
    echo "  - The public key is at:  ~/.ssh/paullm_${target_user}_ed25519.pub"
    echo "  - Copy the public key to any servers you want to connect to"
    echo "  - KeepAlive is configured for long AI sessions"
    echo ""

    if [[ "$DRY_RUN" -eq 1 ]]; then
        echo -e "${YELLOW}This was a DRY RUN. No changes were made.${NC}"
        echo "Run without DRY_RUN=1 to apply changes."
    fi
}

# ── argument parsing ────────────────────────────────────────────────
parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --auto)
                AUTO_MODE=1
                shift
                ;;
            --dry-run)
                DRY_RUN=1
                shift
                ;;
            --with-ai-user)
                CREATE_AI_USER=1
                shift
                ;;
            --ai-user-admin)
                AI_USER_ADMIN=1
                CREATE_AI_USER=1
                shift
                ;;
            --user)
                AI_USERNAME="$2"
                CREATE_AI_USER=1
                shift 2
                ;;
            --port)
                SSH_PORT="$2"
                shift 2
                ;;
            --help|-h)
                cat <<'EOF'
Usage: ./scripts/setup-ssh-host.sh [options]

Configure this Mac as an SSH host for AI coding tools.

Options:
  --auto           Non-interactive mode with defaults
  --dry-run        Show what would be done without making changes
  --with-ai-user   Create a dedicated 'developer' user for AI tools
  --ai-user-admin  Grant the AI user administrator privileges (implies --with-ai-user)
  --user NAME      Use a specific username (implies --with-ai-user)
  --port PORT      Use a custom SSH port (default: 22)
  --help, -h       Show this help message

Examples:
  ./scripts/setup-ssh-host.sh --auto
  ./scripts/setup-ssh-host.sh --with-ai-user --port 2222
  DRY_RUN=1 ./scripts/setup-ssh-host.sh --dry-run
EOF
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                exit 1
                ;;
        esac
    done
}

# ── main ──────────────────────────────────────────────────────────
main() {
    parse_args "$@"
    check_macos

    echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  paullm-ssh host setup${NC}"
    echo -e "${CYAN}  Configure this Mac for AI coding tool access${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════${NC}"
    echo ""

    if [[ "$AUTO_MODE" -eq 0 && "$DRY_RUN" -eq 0 ]]; then
        echo "This script will:"
        echo "  1. Enable Remote Login (SSH)"
        echo "  2. Harden SSH configuration (key-auth only, no root)"
        echo "  3. Configure firewall"
        echo "  4. Generate SSH key pair for AI tools"
        echo "  5. Set up SSH config snippets"
        echo ""

        if ! prompt_yesno "Continue with setup"; then
            echo "Cancelled."
            exit 0
        fi

        if prompt_yesno "Create a dedicated user for AI tools"; then
            CREATE_AI_USER=1
            if [[ "$AI_USERNAME" == "developer" ]]; then
                read -r -p "Username [developer]: " input_user
                AI_USERNAME="${input_user:-developer}"
            fi
        fi
    fi

    step_enable_remote_login
    step_check_sshd
    step_configure_sshd
    step_setup_firewall
    step_generate_host_keys
    step_create_ai_user
    step_generate_client_key
    step_install_authorized_key
    step_setup_ssh_config

    step_print_summary
}

main "$@"
